from fpdf import FPDF
import os
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo could be here
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'Clinical Risk Assessment Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Clinical Risk Predictor', 0, 0, 'C')

class PDFService:
    def __init__(self, output_dir="backend/pdfs"):
        # Fix path absolute
        self.output_dir = os.path.join(os.getcwd(), output_dir)
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_report(self, patient_data: dict, risk_score: float, risk_level: str, llm_summary: str) -> str:
        """
        Generates PDF and returns the absolute file path.
        """
        pdf = PDFReport()
        pdf.add_page()
        
        # 1. Patient Info
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 10, 'Patient Profile', 0, 1)
        pdf.set_font('Helvetica', '', 10)
        
        # Two columns for vitals
        col_width = pdf.w / 2.5
        vitals = [
            f"Age: {patient_data.get('age')} years",
            f"Gender: {patient_data.get('gender')}",
            f"BMI: {patient_data.get('bmi')}",
            f"Glucose: {patient_data.get('blood_glucose_level')} mg/dL",
            f"HbA1c: {patient_data.get('HbA1c_level')}%",
            f"Smoking: {patient_data.get('smoking_history')}"
        ]
        
        for i in range(0, len(vitals), 2):
            pdf.cell(col_width, 8, vitals[i], 0, 0)
            if i+1 < len(vitals):
                pdf.cell(col_width, 8, vitals[i+1], 0, 1)
            else:
                pdf.ln()
                
        pdf.ln(5)
        
        # 2. Risk Assessment
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 10, 'Risk Assessment', 0, 1)
        pdf.set_font('Helvetica', '', 11)
        
        # Color code risk
        if risk_level.lower() == 'high':
            pdf.set_text_color(220, 53, 69) # Red
        elif risk_level.lower() == 'moderate':
            pdf.set_text_color(255, 193, 7) # Yellow/Orange
        else:
            pdf.set_text_color(40, 167, 69) # Green
            
        pdf.cell(0, 10, f"Risk Level: {risk_level.upper()} (Score: {risk_score:.2f})", 0, 1)
        pdf.set_text_color(0, 0, 0) # Reset
        
        pdf.ln(5)
        
        # 3. Clinical Summary (LLM)
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 10, 'AI Clinical Summary', 0, 1)
        pdf.set_font('Helvetica', '', 10)
        pdf.multi_cell(0, 6, llm_summary)
        
        pdf.ln(10)
        
        # 4. Disclaimer
        pdf.set_font('Helvetica', 'I', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI system (BioMistral-7B + XGBoost). It is for informational purposes only and does not constitute a medical diagnosis. Please consult a specialist.")
        
        # Save
        filename = f"report_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        pdf.output(filepath)
        
        return filename  # Return just filename to be served via URL
